<p>If you are using a caching plugin like W3 Total Cache, WP Super Cache, Quick
    Cache etc, then the option "after this time duration" may not show the
    proper time left.</p>

<p>The reason is that caching plugins usually show an &quot;older&quot; version
    of the content, including older digits in the countdown itself.</p>

<p>If you check this option, Countdown Dynamite will use a different function to
    display the digits. This will ensure that the countdown will show the proper
    time left, even if you are using a caching plugin.</p>

<p>The downside is that it may take a little longer for the digits to appear on
    the screen. So, only check this option, if you are using a caching plugin.</p>

<p>If you are using Countdown Dynamite only for the &quot;expire countdown on
    this specific date&quot; or &quot;after visitor sees the content once only&quot;
    options, then you don't need to check the box. These two functions are not
    affected by caching plugins, because their effects are &quot;absolute&quot;
    and not dynamic in nature.</p>