<p>Here you can customize the look of your countdown clock.</p>

<p>The font you select will be applied to both the digits and the labels (hours,
    minutes etc) in the countdown.</p>

<p>You can select to hide some of the labels. For example, if you want to have
    your offer available for  &quot;1 Hour, 30 Minutes, 00 Seconds&quot;, you
    may want to uncheck &quot;Days&quot;, and it will not appear in your
    countdown at all.</p>

<p>You can also change the language of the labels. For example, if you have a
    site in Spanish, you can change &quot;Seconds&quot; to
    &quot;Segundos&quot;.</p>