<p><strong style="color: red">Please read:</strong> The embed code is only meant
    to be used on static HTML sites. For WordPress sites where Countdown
    Dynamite is installed on, please use the plugin's shortcode
    [countdown-dynamite].</p>

<p>You can use this code to show the countdown on static HTML sites.</p>

<p>Highlight the code, copy it and paste it in your page's HTML, where you want
    the countdown to appear. Save your page and upload it to your server.</p>

<p>The static page can be on ANY domain, not just the one you have installed
    WordPress on.</p>

<p>If you add the code to a static site, and later you edit the settings of the
    countdown on this page, your new settings will be automatically applied to
    the static page.</p>

<p>Keep in mind that, if you are using the demo version of Countdown Dynamite to
    test the plugin, you need to be logged in as admin to your WordPress site,
    in order for you to see the timer on static pages.</p>