<p>If you select a specific time duration, for example, &quot;1 Hour, 30
    Minutes, 00 Seconds&quot;, then the countdown will start counting the moment
    someone visits the post/page you have the countdown on. The countdown will
    also start if it's displayed in an index page like your homepage.</p>

<p>The countdown will start from each one of your visitors individually. For
    example, it will show as &quot;1 Hour, 30 Minutes, 00 Seconds&quot; for your
    first visitor. If after 2 days another visitor comes, the countdown will
    start counting down from &quot;1 Hour, 30 Minutes, 00 Seconds&quot; for them
    as well.</p>