<p>Click in the text field and select the exact date and time on which you want
    your offer to end.</p>

<p>Don't forget to select your own Timezone as well. When you installed the
    plugin, it read the timezone value from your WordPress settings and used it
    to set the default timezone value.</p>

<p>You can see the current time in UTC <a href="http://www.worldtimeserver.com/current_time_in_UTC.aspx" target="_blank">here</a>.
    Select a country (and state if applicable) from the left column, to see what
    your local time it is, as well as the UTC offset for it.</p>