<p>If you select this option, then your visitor will only see your offer once.
    This is great for &quot;OTOs&quot; (one-time offers), especially after
    someone has just purchased something from you.</p>

<p>If your visitor visits the post/page again, or reloads it, they will be
    redirected to the URL you selected.</p>

<p>In order to set up this option, go to edit the post/page you want the
    one-time offer to appear on. Then, check the &quot;Enable countdown on this
    post&quot; option in the widget below the content editor text area.</p>

<p>There's no reason to insert a countdown in the post/page, since there will
    not be a countdown within the actual content either.</p>