<p>Add the content you want to be shown above and below the countdown timer,
    until it expires.</p>

<p><strong>ABOVE the timer examples:</strong></p>

<ul>
    <li>Price will go up in:</li>
    <li>This special offer will end in:</li>
</ul>

<p><strong>BELOW the timer examples:</strong></p>

<ul>
    <li>A discounted order link.</li>
    <li>A link to a page with a special offer on your site.</li>
</ul>

<p>Once the countdown reaches zero, the content you specify here will become
    HIDDEN automatically, so your visitors won't be able to access it any more.</p>

<p>You can use the WYSIWYG editor to format the text, add links, images, etc.</p>

<p><strong>Note:</strong> The extra content will be placed above/below the 
    PARAGRAPH containing the counter, not exactly the counter itself.</p>

<p>So, if the paragraph with the counter contains any text before or after the 
    counter shortcode, the content above/below pieces will be added above/below 
    that extra text.</p>