<p>If you select this option, you will be able to make the countdown
    AUTOMATICALLY RESTART for a visitor, aftersome time passes.

<p>EXAMPLE:</p>

<p>Let's say you have set the countdown to 3 hours.</p>

<p>A visitor comes to your page, and the countdown starts counting down.</p>

<p>At some point, the countdown will reach zero.</p>

<p>You can set the countdown restart duration to &quot;2 hours.&quot; This means
    that after 2 more hours have passed, the countdown will start counting down
    again from 3 hours.</p>

<p>This creates an &quot;infinite loop&quot; of customized countdowns for each
    visitor.</p>

<p>You can use this with &quot;odd&quot; durations as well, like:</p>

<p>2 days, 17 hours, 23 minutes and 6 seconds</p>

<p>... which looks less &quot;programmed&quot; than, say &quot;3 hours.&quot;</p>

